### ISSUE TITLE
Viewing lesson standard codes changes column widths

### ISSUE THREAD

**Issue by kyaroch** [andyras/edumap#110]
Currently, if you open up the accordion body to view the standards codes, the column widths will change substantially and the headings will move:

![screen shot 2016-06-07 at 7 51 26 pm](https://cloud.githubusercontent.com/assets/8214544/15879457/fc4d3fb4-2ce9-11e6-93af-8bffc9a1d0de.png)
![screen shot 2016-06-07 at 7 51 33 pm](https://cloud.githubusercontent.com/assets/8214544/15879460/ff5a3d1a-2ce9-11e6-9395-1cd6a8399ddd.png)

This is a bit visually confusing. Since there's nothing in the accordion body except the standards codes, I think it would make sense to make that cell span all remaining columns:

![screen shot 2016-06-07 at 7 50 55 pm](https://cloud.githubusercontent.com/assets/8214544/15879434/d7620e1e-2ce9-11e6-8406-e1f6559df43b.png)
![screen shot 2016-06-07 at 7 50 43 pm](https://cloud.githubusercontent.com/assets/8214544/15879433/d5c85c02-2ce9-11e6-98f5-3b249497611e.png)

The column widths will still change slightly, but not as much. Does this seem reasonable?

**Comment by andyras** [comment]
I noticed that as well. Having the codes span all the remaining columns would be reasonable, though it would be ideal to not have the column widths change.

Perhaps the codes could just fill the entire width?
