### ISSUE TITLE
Allow for users to email list of lessons to themselves

### ISSUE THREAD

**Issue by pjsier** [andyras/edumap#53]
We've discussed this a bit, but wanted to record it as an issue. Basic idea is that someone could check boxes next to lessons and then have them emailed to themselves (so we could allow people to store things without needing them to create any account)

**Comment by hwayne** [comment]
Is anybody planning on taking this on? If not I have a few ideas on how to tackle it.

**Comment by pjsier** [comment]
@hwayne right now I don't think anyone has claimed it, so if you want to take a stab at it that'd be great!

**Comment by hwayne** [comment]
Lesson selection and storage added in https://github.com/andyras/edumap/pull/63, emailing of lessons to be completed after #60.

**Comment by kyaroch** [comment]
I've started working on this, mainly with an eye to making sure that I know how to do it, rather than setting it into any definite form. If @hwayne or anyone else has ideas on how to handle it, I'd be happy to discuss them.

**Comment by vingkan** [comment]
@kyaroch Finished this, just needs a few UI updates.
